### ISSUE TITLE
Implementing common frontend interfaces

### ISSUE THREAD

**Issue by Riyasfareed** [UOR-Project-Team/ERP-System-Frontend#2]
Implement And push the Frontend Interface and structure

**Comment by NuvinduSenarathne** [comment]
- [ ] Create front-end react app
- [ ] Create folder structure
- [ ] Create header component
- [ ] Create collapse sidepanel component
- [ ] Create expand sidepanel component
- [ ] Import components and complete dashboard component
- [ ] Create routes to other interfaces

**Comment by NuvinduSenarathne** [comment]
- [ ] Update the header according to requirements

**Comment by NuvinduSenarathne** [comment]
- [ ] Update the collapsed side panel according to reuirements
